import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import { AuthProvider } from "@propelauth/nextjs/client";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "TerraPodium",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />
        {children}
      </body>
      <AuthProvider authUrl={process.env.NEXT_PUBLIC_AUTH_URL}></AuthProvider>
    </html>
  );
}
